# Copyright (c) 2025 SAP SE or an SAP affiliate company and sprint contributors
# SPDX-License-Identifier: Apache-2.0
# SPRINT Inference Configuration
# Example configuration file for inference runs

# Model settings
model_name: "roberta-base" # Example with non fine-tuned-model just for testing
#model_name: "roberta-base_adam_bc_falora_r16_a16_kaiming_uniform_bolt_gelu_softmax__sst2" # Example with fine-tuned model
test_dataset: "sst2" # "qnli"
batch_size: 2
n_samples: 2

# Device configuration (list of devices for multi-process)
devices: ["cpu", "cpu"]
# devices: ["cuda:0", "cuda:1"] in the same machine. If different machines then ["cuda:0", "cuda:0"]

# Model configuration overrides
hidden_act: "bolt_gelu"
softmax: "softmax"
cap: 50.0
lora_type: "falora"
lora_init_method: "normal"
lora_layers: ["query", "key", "value", "dense"]
lora_rank: 16
lora_alpha: 16

# Execution settings
encrypted: true # whether to use secure inference with CrypTen
clear_embedding: true # whether to leave the embedding layer in cleartext
clear_non_trainable: true # whether to leave non-trainable layers in cleartext
verbose: true 
world_size: 2 # number of parties in CrypTen
debug: true 
profile: true # whether to profile the execution time and communication
multiprocess: true # whether to use multi-process for inference



